---
version: "3"
services:
  folding-at-home:
    image: yurinnick/folding-at-home
    container_name: folding-at-home
    environment:
      - USER=Anonymous
      - TEAM=0
      - ENABLE_GPU=false
      - ENABLE_SMP=true
    volumes:
      - /path/to/fahdata:/opt/fahclient/work
    ports:
      - 7396:7396
      - 36330:36330
    command:
      - --allow 0/0
      - --web-allow 0/0
    restart: unless-stopped
